name: RisingSpire
main: com.statuswoe.minecraft.RisingSpire
version: 0.0.1

commands:
  brent:
    description: This is a demo command.
    usage: /<command>
  coord:
    description: This is a demo command.
    usage: /<command>
